--liquibase formatted sql
--changeset init_clan_table_sql:1

create table clan (
        id int8 generated by default as identity,
        gold int8 not null check (gold>=0 AND gold<=9223372036854775807),
        name varchar(255) not null,
        primary key (id)
);

alter table clan
       add constraint constraint00000001 unique (name);

--changeset init_clan_gold_tr_sql:2
create table clan_gold_tr (
        id int8 not null AUTO_INCREMENT,

        clanId int8 not null,
        operationOwner varchar(255) not null,
        operationName varchar(255) not null,
        operationGoal varchar(255) not null,

        goldBefore int8,
        goldDiff int8,
        goldAfter int8,

        operationState varchar(255) not null,

        createAt timestamp not null,
        endAt timestamp,

        primary key (id)
);

alter table clan_gold_tr
   add constraint constraint00000002
   foreign key (clanId)
   references clan;

